spring.application.name=na_zvah
na_zvah.version=0.0.1

# Cloud SQL
spring.datasource.url=jdbc:postgresql:///${DB_NAME:zvah}?cloudSqlInstance=${DB_CONNECTION_NAME:projectppi-508514:us-central1:ink}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER:ink_user_nib}
spring.datasource.password=${DB_PASSWORD:ink_user_nib}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# After Cloud Assist