spring.application.name=na_zvaH

na_zvaH.version=0.0.1

user.home=/Users/rakup
# Cloud SQL Configuration
spring.cloud.gcp.sql.instance-connection-name=${DB_CONNECTION_NAME:projectppi-508514:us-central1:ink}
spring.cloud.gcp.sql.database-name=${DB_NAME:zvaH}

# Database Credentials
spring.datasource.username=${DB_USER:ink_user_nib}
spring.datasource.password=${DB_PASSWORD:ink_user_nib}

#spring.cloud.gcp.credentials.location=file:${user.home}/local-gcp-key.json

# Optional: Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Properties for GCP
server.port=${PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Comment for auto deploy